# fly.toml file generated for bae on 2022-01-11T19:59:24-06:00

app = "bae"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
NODE_ENV = "production"

[experimental]
allowed_public_ports = []
auto_rollback = true
